# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: cli
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: lets
    id: lets
    goos:
      - linux
      - windows
    ldflags:
      - -X github.com/let-sh/cli/cmd.version={{.Version}}
  - env:
      - CGO_ENABLED=0
    binary: let
    id: lets_macos
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X github.com/let-sh/cli/cmd.version={{.Version}}
#    hooks:
#      post: gon gon.hcl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  commit_author:
    name: Fred Liang
    email: fred@oasis.ac
  homepage: "https://alpha.let.sh.ch/"
  description: "let.sh command line interface."
release:
  github:
    owner: let-sh
    name: cli
  prerelease: auto
blobs:
  -
    provider: s3
    endpoint: let-cli.oss-cn-hongkong.aliyuncs.com
    region: cn-hongkong
    bucket: "."
    folder: "/"