# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: cli
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    - chmod +x ./scripts/gen_version.sh
    - ./scripts/gen_version.sh
    # if npx not install, install it
    -  command -v upx >/dev/null 2>&1 || { brew install upx >&2; }
builds:
  - env:
      - CGO_ENABLED=0
    binary: lets
    id: lets
    goos:
      - linux
      - windows
    ldflags:
      - -X github.com/let-sh/cli/cmd.version={{.Version}}
      - -s
      - -w
    hooks:
      post:
        - upx {{ .Path }}
  - env:
      - CGO_ENABLED=0
    binary: lets
    id: lets_macos
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X github.com/let-sh/cli/cmd.version={{.Version}}
      - -s
      - -w
    hooks:
      post:
        - upx {{ .Path }}
        - gon gon.hcl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
scoop:
  commit_author:
    name: Fred Liang
    email: fred@oasis.ac
  homepage: "https://alpha.let.sh.ch/"
  description: "let.sh command line interface."
release:
  github:
    owner: let-sh
    name: cli
  prerelease: auto
  extra_files:
    - glob: ./dist/lets_macos_darwin_amd64/*.zip
    - glob: ./dist/lets_macos_darwin_amd64/*.dmg
blobs:
  -
    provider: s3
    endpoint: let-cli.oss-cn-hongkong.aliyuncs.com
    region: cn-hongkong
    bucket: "."
    folder: "."
    extra_files:
      - glob: ./version
      - glob: ./scripts/install.sh
      - glob: ./dist/lets_macos_darwin_amd64/*.zip
      - glob: ./dist/lets_macos_darwin_amd64/*.dmg